-- Up Migration
--
-- Initial schema for the 7 Star Battery POS rewrite.
--
-- THIS FILE IS THE SOURCE OF TRUTH for the database schema. It must be
-- reconciled against the legacy 7STARBATTERYPOS.mdf in phase 0 before any
-- production data is loaded -- see api/README.md.

-- =============================================================================
-- 7 Star Battery POS — PostgreSQL schema
-- Reconstructed from the ASP.NET Core 8 EF Core model classes.
--
-- SOURCE OF TRUTH WARNING
-- The legacy project has NO EF migrations for business tables; the live schema
-- exists only inside 7STARBATTERYPOS.mdf. This file is reconstructed from the
-- 58 model classes in Models/ plus the raw SQL in Controllers/. It therefore
-- covers columns and types, but CANNOT know:
--   * indexes, defaults and check constraints defined in SSMS
--   * seed rows (chart of accounts, form_head/form/forms_action permission IDs)
--   * any column present in SQL Server but absent from the C# model
-- Reconcile against a scripted-out .mdf before loading production data.
--
-- CONVENTIONS
--   * snake_case identifiers (legacy name kept in a comment where it differed)
--   * money      -> numeric(18,2)
--   * quantities -> numeric(18,3)
--   * every table that had CreatedAt/UpdatedAt/CreatedBy/UpdatedBy (BaseModel)
--     keeps them as created_at/updated_at/created_by/updated_by
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================================
-- 1. REFERENCE / ORGANISATION
-- =============================================================================

CREATE TABLE branch (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL,
    address     text,
    longitude   numeric(12,7) NOT NULL DEFAULT 0,
    latitude    numeric(12,7) NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer     NOT NULL DEFAULT 0,
    updated_by  integer     NOT NULL DEFAULT 0
);

CREATE TABLE province (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE city (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE department (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

-- Legacy: single-row table, Id defaulted to 0.
CREATE TABLE setting (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text,
    phone            text,
    address          text,
    email            text,
    image            text,
    delivery_charges numeric(18,2) NOT NULL DEFAULT 0
);

-- =============================================================================
-- 2. CATALOG
-- =============================================================================

CREATE TABLE brand (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    other_name  text,
    company_id  integer NOT NULL DEFAULT 0,      -- legacy: companyid
    branch_id   integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    is_raw      boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

-- Legacy table name was misspelled "Catagory".
CREATE TABLE category (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    other_name  text,
    image_path  text,
    company_id  integer NOT NULL DEFAULT 0,
    branch_id   integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    is_raw      boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

-- Finished goods. Legacy columns were lowercase-unquoted (id, name, price...).
CREATE TABLE product (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text,
    other_name        text,
    price             numeric(18,2) NOT NULL DEFAULT 0,  -- cost price, drives COGS
    sale_price        numeric(18,2) NOT NULL DEFAULT 0,
    least_price       numeric(18,2) NOT NULL DEFAULT 0,
    open_qty          numeric(18,3) NOT NULL DEFAULT 0,
    company_id        integer NOT NULL DEFAULT 0,
    brand_id          integer REFERENCES brand(id),
    category_id       integer REFERENCES category(id),  -- legacy: catagoryid
    unit_of_measure   text,
    company_barcode   text,                             -- legacy: companybarcoad
    reorder_level     integer NOT NULL DEFAULT 0,
    brand_discount    numeric(18,2) NOT NULL DEFAULT 0,
    shelf_number      integer NOT NULL DEFAULT 0,
    image_path        bytea,                            -- consider object storage
    branch_id         integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    is_active         boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    created_by        integer NOT NULL DEFAULT 0,
    updated_by        integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_product_branch  ON product(branch_id);
CREATE INDEX idx_product_active  ON product(is_active) WHERE is_active;

-- Raw materials consumed by Production.
CREATE TABLE raw_product (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    price       numeric(18,2) NOT NULL DEFAULT 0,
    reorder     numeric(18,3) NOT NULL DEFAULT 0,
    brand_id    integer REFERENCES brand(id),
    cat_id      integer REFERENCES category(id),
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

-- =============================================================================
-- 3. PARTIES
-- =============================================================================

CREATE TABLE customer (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    code        text,
    phone       text,
    mobile      text,
    address     text,
    email       text,
    cnic        text,
    province    text,
    city        text,
    is_active   boolean NOT NULL DEFAULT true,
    branch_id   integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    account_id  integer NOT NULL DEFAULT 0,   -- FK to account(account_id), see §5
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_customer_branch ON customer(branch_id);

-- Walk-in ("cash customer") captured inline on a sale.
-- Legacy behaviour: customer.id = 1 AND account_id = 1010201 triggers this path.
CREATE TABLE sale_customer (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text,
    phone      text,
    address    text,
    branch_id  integer NOT NULL DEFAULT 0 REFERENCES branch(id)
);
CREATE INDEX idx_sale_customer_phone ON sale_customer(branch_id, phone);

CREATE TABLE supplier (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text,
    code           text,
    branch_id      integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    account_no     integer NOT NULL DEFAULT 0,
    contact_person text,
    cnic           text,
    phone          text,
    email          text,
    address        text,
    ntn            text,
    strn           text,
    city           text,
    company        text,
    is_active      boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    created_by     integer NOT NULL DEFAULT 0,
    updated_by     integer NOT NULL DEFAULT 0
);

CREATE TABLE employee (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    text NOT NULL,
    last_name     text,
    phone         text,
    mobile        text,
    cnic          text,
    gender        text,
    code          text,
    img           text,
    province      text,
    city          text,
    basic_salary  numeric(18,2) NOT NULL DEFAULT 0,
    branch_id     integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    account_no    integer NOT NULL DEFAULT 0,
    department_id integer REFERENCES department(id),
    dob           date,
    join_date     date,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    created_by    integer NOT NULL DEFAULT 0,
    updated_by    integer NOT NULL DEFAULT 0
);

-- =============================================================================
-- 4. AUTH & PERMISSIONS
--    Legacy stored passwords in PLAINTEXT and compared them with string
--    equality. Replaced here with a hash column; the ETL must force a reset.
-- =============================================================================

CREATE TABLE role (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL,
    branch_id  integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0
);

-- Legacy: DbSet<UserLogins> UserLoginss -> table "UserLogins"
CREATE TABLE user_logins (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      text        NOT NULL UNIQUE,
    password_hash text        NOT NULL,   -- bcrypt/argon2; legacy was PLAINTEXT
    role_id       integer     REFERENCES role(id),
    emp_id        integer     NOT NULL DEFAULT 0,  -- 0 == super admin
    branch_id     integer     NOT NULL DEFAULT 0 REFERENCES branch(id),
    is_active     boolean     NOT NULL DEFAULT true,
    last_login_at timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    created_by    integer     NOT NULL DEFAULT 0,
    updated_by    integer     NOT NULL DEFAULT 0
);

-- Permission tree: head -> form -> action. The IDs are referenced as literals
-- throughout the legacy Razor layout (HasHead(2), HasAction(12, 4011), ...),
-- so these three tables MUST be seeded with the exact rows from the .mdf.
CREATE TABLE form_head (
    head_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    head_name text NOT NULL,
    code      integer NOT NULL,
    sr        integer NOT NULL DEFAULT 0
);

CREATE TABLE form (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    head_id   integer NOT NULL REFERENCES form_head(head_id),
    form_name text    NOT NULL,
    sub       text,
    sr        integer NOT NULL DEFAULT 0,
    ids       integer NOT NULL DEFAULT 0,
    form_code integer NOT NULL
);

CREATE TABLE forms_action (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id     integer NOT NULL REFERENCES form(id),
    action_name text    NOT NULL,          -- View / New / Edit / Delete / Print
    sr          integer NOT NULL DEFAULT 0,
    action_code integer NOT NULL
);

CREATE TABLE role_assign (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    integer NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    head_id    integer NOT NULL,
    form_id    integer NOT NULL,
    action_id  integer NOT NULL,
    branch_id  integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0,
    UNIQUE (role_id, head_id, form_id, action_id)
);
CREATE INDEX idx_role_assign_role ON role_assign(role_id);

CREATE TABLE user_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id     integer,
    branch_id  integer NOT NULL DEFAULT 0,
    user_id    integer NOT NULL DEFAULT 0,
    username   text,
    form       text,
    action     text,
    detail     text,
    datetime   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_log_time ON user_log(datetime DESC);
CREATE INDEX idx_user_log_form ON user_log(form, inv_id);

-- =============================================================================
-- 5. CHART OF ACCOUNTS  (3 levels + optional "third" grouping)
--    Codes are composed, e.g. 1010201 = head 1 / subhead 01 / ... / account 01.
--    Hardcoded codes used by the posting engine are listed in db/accounts.md.
-- =============================================================================

CREATE TABLE account_head (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text    NOT NULL,
    code integer NOT NULL UNIQUE
);

CREATE TABLE account_sub_head (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text    NOT NULL,
    code       integer NOT NULL,
    head_code  integer NOT NULL,
    head_id    integer NOT NULL REFERENCES account_head(id),
    branch_id  integer NOT NULL DEFAULT 0,
    is_fixed   boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0
);

CREATE TABLE account_third (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text,
    account_id    integer NOT NULL DEFAULT 0,
    head_id       integer NOT NULL REFERENCES account_head(id),
    sub_head_id   integer NOT NULL REFERENCES account_sub_head(id),
    head_code     integer NOT NULL,
    sub_head_code integer NOT NULL,
    branch_id     integer NOT NULL DEFAULT 0,
    is_fixed      boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    created_by    integer NOT NULL DEFAULT 0,
    updated_by    integer NOT NULL DEFAULT 0
);

-- account_id holds the composed posting code (e.g. 1010402) and is what the
-- transactions table actually references.
CREATE TABLE account (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    account_id  integer NOT NULL UNIQUE,
    head_id     integer NOT NULL REFERENCES account_head(id),
    sub_head_id integer NOT NULL REFERENCES account_sub_head(id),
    head_code   integer NOT NULL,
    sub_code    integer NOT NULL,
    third       integer NOT NULL DEFAULT 0,
    third_code  integer NOT NULL DEFAULT 0,
    com_id      integer NOT NULL DEFAULT 0,
    branch_id   integer NOT NULL DEFAULT 0,
    is_fixed    boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

CREATE TABLE account_opening (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL REFERENCES account(account_id),
    branch_id  integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    user_id    integer NOT NULL DEFAULT 0,
    date       date    NOT NULL,
    dr         numeric(18,2) NOT NULL DEFAULT 0,
    cr         numeric(18,2) NOT NULL DEFAULT 0,
    detail     text
);

-- -----------------------------------------------------------------------------
-- GENERAL LEDGER
-- Legacy column order (recovered from positional INSERTs, NOT from the C# class):
--   Date, Datetime, InvId, Vtype, Dr, Cr, AccountId, Detail, VoucherNo,
--   TransId, BranchId
-- The ETL must map by this order, not by the model property order.
--
-- trans_id groups the legs of one balanced voucher. The CHECK below is what the
-- legacy system lacked: it rejects a leg that is neither a debit nor a credit.
-- Per-voucher balance is enforced in the application layer (see §NOTE).
-- -----------------------------------------------------------------------------
CREATE TABLE transactions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date          NOT NULL,
    datetime   timestamptz   NOT NULL DEFAULT now(),
    inv_id     integer       NOT NULL DEFAULT 0,
    vtype      text          NOT NULL,   -- SINV, PINV, SRET, PRET, CRV, CPV, BRV, BPV, JV
    dr         numeric(18,2) NOT NULL DEFAULT 0,
    cr         numeric(18,2) NOT NULL DEFAULT 0,
    account_id integer       NOT NULL REFERENCES account(account_id),
    detail     text,
    voucher_no integer       NOT NULL,
    trans_id   integer       NOT NULL,
    branch_id  integer       NOT NULL DEFAULT 0 REFERENCES branch(id),
    CONSTRAINT chk_transactions_one_sided CHECK (dr >= 0 AND cr >= 0 AND (dr = 0) <> (cr = 0))
);
CREATE INDEX idx_transactions_account_date ON transactions(account_id, date);
CREATE INDEX idx_transactions_voucher      ON transactions(trans_id);
CREATE INDEX idx_transactions_source       ON transactions(vtype, inv_id);
CREATE INDEX idx_transactions_branch_date  ON transactions(branch_id, date);

-- Replaces "SELECT ISNULL(MAX(TransId),0)+1" — that was a race condition.
CREATE SEQUENCE transactions_trans_id_seq AS integer START 1;
CREATE SEQUENCE transactions_voucher_no_seq AS integer START 1;

-- =============================================================================
-- 6. VOUCHERS (CRV / CPV / BRV / BPV / JV)
-- =============================================================================

CREATE TABLE voucher_master (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date    NOT NULL,
    tran_id    integer NOT NULL,
    branch_id  integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    inv_id     integer NOT NULL DEFAULT 0,
    account_id integer NOT NULL,
    amount     numeric(18,2) NOT NULL DEFAULT 0,
    amount1    numeric(18,2) NOT NULL DEFAULT 0,
    type       text,          -- CRV / CPV / BRV / BPV / JV
    detail     text,
    vno        text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_voucher_master_type_date ON voucher_master(type, date);

CREATE TABLE voucher_detail (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trans_id       integer NOT NULL,
    inv_id         integer NOT NULL DEFAULT 0,   -- legacy: Invid
    account_id     integer NOT NULL,
    detail         text,
    vtype          text,
    cheque_status  text,
    acc_name       text,
    cheque_date    date,
    cheque_no      text,
    dr             numeric(18,2) NOT NULL DEFAULT 0,
    cr             numeric(18,2) NOT NULL DEFAULT 0
);
CREATE INDEX idx_voucher_detail_inv ON voucher_detail(vtype, inv_id);

-- =============================================================================
-- 7. SALES
-- =============================================================================

CREATE TABLE sale (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           date    NOT NULL,
    cust_id        integer NOT NULL REFERENCES customer(id),
    sale_cust_id   integer REFERENCES sale_customer(id),
    branch_id      integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    gross_total    numeric(18,2) NOT NULL DEFAULT 0,
    sub_total      numeric(18,2) NOT NULL DEFAULT 0,
    discount       numeric(18,2) NOT NULL DEFAULT 0,
    service        numeric(18,2) NOT NULL DEFAULT 0,
    net_total      numeric(18,2) NOT NULL DEFAULT 0,
    received       numeric(18,2) NOT NULL DEFAULT 0,
    remaining      numeric(18,2) NOT NULL DEFAULT 0,
    notes          text,
    inv_type       text NOT NULL DEFAULT 'SINV',
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    created_by     integer NOT NULL DEFAULT 0,
    updated_by     integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_sale_branch_date ON sale(branch_id, date DESC);
CREATE INDEX idx_sale_customer    ON sale(cust_id);

CREATE TABLE sale_detail (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id   integer NOT NULL REFERENCES sale(id) ON DELETE CASCADE,
    pid       integer NOT NULL REFERENCES product(id),
    pname     text,
    price     numeric(18,2) NOT NULL DEFAULT 0,
    qty       numeric(18,3) NOT NULL DEFAULT 0,
    total     numeric(18,2) NOT NULL DEFAULT 0,
    discount  numeric(18,2) NOT NULL DEFAULT 0,
    net_total numeric(18,2) NOT NULL DEFAULT 0
);
CREATE INDEX idx_sale_detail_sale ON sale_detail(sale_id);

CREATE TABLE sale_return (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         date    NOT NULL,
    sale_id      integer REFERENCES sale(id),
    cust_id      integer NOT NULL REFERENCES customer(id),
    sale_cust_id integer REFERENCES sale_customer(id),
    branch_id    integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    gross_total  numeric(18,2) NOT NULL DEFAULT 0,
    sub_total    numeric(18,2) NOT NULL DEFAULT 0,
    discount     numeric(18,2) NOT NULL DEFAULT 0,
    service      numeric(18,2) NOT NULL DEFAULT 0,
    net_total    numeric(18,2) NOT NULL DEFAULT 0,
    paid         numeric(18,2) NOT NULL DEFAULT 0,
    remaining    numeric(18,2) NOT NULL DEFAULT 0,
    notes        text,
    inv_type     text NOT NULL DEFAULT 'SRET',
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    created_by   integer NOT NULL DEFAULT 0,
    updated_by   integer NOT NULL DEFAULT 0
);

CREATE TABLE sale_return_detail (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id   integer NOT NULL REFERENCES sale_return(id) ON DELETE CASCADE,
    pid       integer NOT NULL REFERENCES product(id),
    pname     text,
    price     numeric(18,2) NOT NULL DEFAULT 0,
    qty       numeric(18,3) NOT NULL DEFAULT 0,
    total     numeric(18,2) NOT NULL DEFAULT 0,
    discount  numeric(18,2) NOT NULL DEFAULT 0,
    net_total numeric(18,2) NOT NULL DEFAULT 0
);

-- "Hold sale" / lease — parked basket, no ledger impact until converted.
CREATE TABLE lease_sale (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date    NOT NULL,
    branch_id  integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    cust_id    integer NOT NULL REFERENCES customer(id),
    status     text,
    note       text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0
);

CREATE TABLE lease_sale_detail (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id integer NOT NULL REFERENCES lease_sale(id) ON DELETE CASCADE,
    pid     integer NOT NULL REFERENCES product(id),
    pname   text,
    status  text,
    qty     numeric(18,3) NOT NULL DEFAULT 0
);

-- =============================================================================
-- 8. PURCHASES
-- =============================================================================

CREATE TABLE purchase (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date    NOT NULL,
    sup_id      integer NOT NULL REFERENCES supplier(id),
    branch_id   integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    gross_total numeric(18,2) NOT NULL DEFAULT 0,
    sub_total   numeric(18,2) NOT NULL DEFAULT 0,
    discount    numeric(18,2) NOT NULL DEFAULT 0,
    net_total   numeric(18,2) NOT NULL DEFAULT 0,
    paid        numeric(18,2) NOT NULL DEFAULT 0,
    rent        numeric(18,2) NOT NULL DEFAULT 0,
    remaining   numeric(18,2) NOT NULL DEFAULT 0,
    notes       text,
    inv_type    text NOT NULL DEFAULT 'PINV',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_purchase_branch_date ON purchase(branch_id, date DESC);

CREATE TABLE purchase_detail (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id integer NOT NULL REFERENCES purchase(id) ON DELETE CASCADE,
    pid         integer NOT NULL,
    pname       text,
    price       numeric(18,2) NOT NULL DEFAULT 0,
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    total       numeric(18,2) NOT NULL DEFAULT 0,
    discount    numeric(18,2) NOT NULL DEFAULT 0,
    net_total   numeric(18,2) NOT NULL DEFAULT 0
);
CREATE INDEX idx_purchase_detail_purchase ON purchase_detail(purchase_id);

CREATE TABLE purchase_return (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date    NOT NULL,
    sup_id      integer NOT NULL REFERENCES supplier(id),
    branch_id   integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    gross_total numeric(18,2) NOT NULL DEFAULT 0,
    sub_total   numeric(18,2) NOT NULL DEFAULT 0,
    discount    numeric(18,2) NOT NULL DEFAULT 0,
    net_total   numeric(18,2) NOT NULL DEFAULT 0,
    received    numeric(18,2) NOT NULL DEFAULT 0,
    rent        numeric(18,2) NOT NULL DEFAULT 0,
    remaining   numeric(18,2) NOT NULL DEFAULT 0,
    notes       text,
    inv_type    text NOT NULL DEFAULT 'PRET',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

CREATE TABLE purchase_return_detail (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id integer NOT NULL REFERENCES purchase_return(id) ON DELETE CASCADE,
    pid         integer NOT NULL,
    pname       text,
    price       numeric(18,2) NOT NULL DEFAULT 0,
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    total       numeric(18,2) NOT NULL DEFAULT 0,
    discount    numeric(18,2) NOT NULL DEFAULT 0,
    net_total   numeric(18,2) NOT NULL DEFAULT 0
);

-- =============================================================================
-- 9. DEMAND ORDER / INTER-BRANCH TRANSFER
--    type discriminates raw vs finished goods; the same three tables serve both
--    the Raw Item and Finish Item menu branches.
--    Flow: demand_order -> do_request -> (approve) -> do_received
-- =============================================================================

CREATE TABLE demand_order (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date    NOT NULL,
    from_branch integer NOT NULL REFERENCES branch(id),
    to_branch   integer NOT NULL REFERENCES branch(id),
    type        text,        -- 'RAW' | 'FINISH'
    status      text,
    note        text,
    gross       numeric(18,2) NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

CREATE TABLE demand_order_detail (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id  integer NOT NULL REFERENCES demand_order(id) ON DELETE CASCADE,
    pid     integer NOT NULL,
    pname   text,
    qty     numeric(18,3) NOT NULL DEFAULT 0,
    inv_qty numeric(18,3) NOT NULL DEFAULT 0,
    price   numeric(18,2) NOT NULL DEFAULT 0,
    total   numeric(18,2) NOT NULL DEFAULT 0,
    status  text
);

CREATE TABLE do_request (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    do_id       integer REFERENCES demand_order(id),
    from_branch integer NOT NULL REFERENCES branch(id),
    to_branch   integer NOT NULL REFERENCES branch(id),
    date        date    NOT NULL,
    note        text,
    type        text,
    status      text,
    is_req      boolean NOT NULL DEFAULT true,
    gross       numeric(18,2) NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

CREATE TABLE do_request_detail (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id  integer NOT NULL REFERENCES do_request(id) ON DELETE CASCADE,
    pid     integer NOT NULL,
    pname   text,
    qty     numeric(18,3) NOT NULL DEFAULT 0,
    inv_qty numeric(18,3) NOT NULL DEFAULT 0,
    price   numeric(18,2) NOT NULL DEFAULT 0,
    total   numeric(18,2) NOT NULL DEFAULT 0,
    status  text
);

CREATE TABLE do_received (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    do_req_id     integer REFERENCES do_request(id),
    from_branch   integer NOT NULL REFERENCES branch(id),
    to_branch     integer NOT NULL REFERENCES branch(id),
    date          date    NOT NULL,
    note          text,
    type          text,
    received_by   text,
    cargo_expense numeric(18,2) NOT NULL DEFAULT 0,
    gross         numeric(18,2) NOT NULL DEFAULT 0,
    net           numeric(18,2) NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    created_by    integer NOT NULL DEFAULT 0,
    updated_by    integer NOT NULL DEFAULT 0
);

CREATE TABLE do_received_detail (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id integer NOT NULL REFERENCES do_received(id) ON DELETE CASCADE,
    pid    integer NOT NULL,
    pname  text,
    qty    numeric(18,3) NOT NULL DEFAULT 0,
    price  numeric(18,2) NOT NULL DEFAULT 0,
    total  numeric(18,2) NOT NULL DEFAULT 0
);

-- =============================================================================
-- 10. PRODUCTION  (raw materials -> finished product)
-- =============================================================================

CREATE TABLE production (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           date    NOT NULL,
    branch_id      integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    pid            integer NOT NULL REFERENCES product(id),
    qty            integer NOT NULL DEFAULT 0,
    note           text,
    labor_cost     numeric(18,2) NOT NULL DEFAULT 0,
    electric_cost  numeric(18,2) NOT NULL DEFAULT 0,
    other_cost     numeric(18,2) NOT NULL DEFAULT 0,
    material_cost  numeric(18,2) NOT NULL DEFAULT 0,
    extra          numeric(18,2) NOT NULL DEFAULT 0,
    extra1         numeric(18,2) NOT NULL DEFAULT 0,
    per_unit       numeric(18,2) NOT NULL DEFAULT 0,
    total_cost     numeric(18,2) NOT NULL DEFAULT 0,
    gross_total    numeric(18,2) NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    created_by     integer NOT NULL DEFAULT 0,
    updated_by     integer NOT NULL DEFAULT 0
);

CREATE TABLE production_detail (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id integer NOT NULL REFERENCES production(id) ON DELETE CASCADE,
    pid    integer NOT NULL REFERENCES raw_product(id),
    pname  text,
    price  numeric(18,2) NOT NULL DEFAULT 0,
    qty    numeric(18,3) NOT NULL DEFAULT 0,
    total  numeric(18,2) NOT NULL DEFAULT 0
);

-- =============================================================================
-- 11. LAB  (battery repair / servicing intake -> work -> invoice)
-- =============================================================================

CREATE TABLE lab_received (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date    NOT NULL,
    cust_id    integer NOT NULL REFERENCES customer(id),
    branch_id  integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    note       text,
    status     text,
    gross      numeric(18,2) NOT NULL DEFAULT 0,
    other      numeric(18,2) NOT NULL DEFAULT 0,
    net        numeric(18,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0
);

CREATE TABLE lab_received_detail (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id integer NOT NULL REFERENCES lab_received(id) ON DELETE CASCADE,
    pid    integer NOT NULL,
    pname  text,
    status text,
    qty    numeric(18,3) NOT NULL DEFAULT 0,
    price  numeric(18,2) NOT NULL DEFAULT 0,
    total  numeric(18,2) NOT NULL DEFAULT 0,
    ready  date,
    detail text
);

CREATE TABLE lab (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date    NOT NULL,
    lab_id     integer REFERENCES lab_received(id),
    branch_id  integer NOT NULL DEFAULT 0 REFERENCES branch(id),
    cust_id    integer NOT NULL REFERENCES customer(id),
    gross      numeric(18,2) NOT NULL DEFAULT 0,
    received   numeric(18,2) NOT NULL DEFAULT 0,
    remaining  numeric(18,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0
);

CREATE TABLE lab_detail (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id integer NOT NULL REFERENCES lab(id) ON DELETE CASCADE,
    pid    integer NOT NULL,
    pname  text,
    price  numeric(18,2) NOT NULL DEFAULT 0,
    qty    numeric(18,3) NOT NULL DEFAULT 0,
    total  numeric(18,2) NOT NULL DEFAULT 0
);

-- Raw materials consumed during lab work.
CREATE TABLE lab_used (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id integer NOT NULL,
    bid    integer NOT NULL DEFAULT 0,
    pid    integer NOT NULL,
    pname  text,
    date   date NOT NULL,
    price  numeric(18,2) NOT NULL DEFAULT 0,
    qty    numeric(18,3) NOT NULL DEFAULT 0,
    total  numeric(18,2) NOT NULL DEFAULT 0
);

-- =============================================================================
-- NOTE — voucher balance enforcement
-- The legacy posting engine writes unbalanced vouchers (see db/accounts.md).
-- Once historical data is cleaned, enable this as a deferred constraint trigger
-- so every trans_id must net to zero at commit time:
--
--   CREATE FUNCTION assert_voucher_balanced() RETURNS trigger AS $$
--   BEGIN
--     IF (SELECT sum(dr) - sum(cr) FROM transactions WHERE trans_id = NEW.trans_id) <> 0 THEN
--       RAISE EXCEPTION 'Voucher % is unbalanced', NEW.trans_id;
--     END IF;
--     RETURN NULL;
--   END $$ LANGUAGE plpgsql;
--
--   CREATE CONSTRAINT TRIGGER trg_voucher_balanced
--     AFTER INSERT OR UPDATE ON transactions
--     DEFERRABLE INITIALLY DEFERRED
--     FOR EACH ROW EXECUTE FUNCTION assert_voucher_balanced();
-- =============================================================================


-- Down Migration
DROP SEQUENCE IF EXISTS transactions_voucher_no_seq;
DROP SEQUENCE IF EXISTS transactions_trans_id_seq;
DROP TABLE IF EXISTS lab_used CASCADE;
DROP TABLE IF EXISTS lab_detail CASCADE;
DROP TABLE IF EXISTS lab CASCADE;
DROP TABLE IF EXISTS lab_received_detail CASCADE;
DROP TABLE IF EXISTS lab_received CASCADE;
DROP TABLE IF EXISTS production_detail CASCADE;
DROP TABLE IF EXISTS production CASCADE;
DROP TABLE IF EXISTS do_received_detail CASCADE;
DROP TABLE IF EXISTS do_received CASCADE;
DROP TABLE IF EXISTS do_request_detail CASCADE;
DROP TABLE IF EXISTS do_request CASCADE;
DROP TABLE IF EXISTS demand_order_detail CASCADE;
DROP TABLE IF EXISTS demand_order CASCADE;
DROP TABLE IF EXISTS purchase_return_detail CASCADE;
DROP TABLE IF EXISTS purchase_return CASCADE;
DROP TABLE IF EXISTS purchase_detail CASCADE;
DROP TABLE IF EXISTS purchase CASCADE;
DROP TABLE IF EXISTS lease_sale_detail CASCADE;
DROP TABLE IF EXISTS lease_sale CASCADE;
DROP TABLE IF EXISTS sale_return_detail CASCADE;
DROP TABLE IF EXISTS sale_return CASCADE;
DROP TABLE IF EXISTS sale_detail CASCADE;
DROP TABLE IF EXISTS sale CASCADE;
DROP TABLE IF EXISTS voucher_detail CASCADE;
DROP TABLE IF EXISTS voucher_master CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS account_opening CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS account_third CASCADE;
DROP TABLE IF EXISTS account_sub_head CASCADE;
DROP TABLE IF EXISTS account_head CASCADE;
DROP TABLE IF EXISTS user_log CASCADE;
DROP TABLE IF EXISTS role_assign CASCADE;
DROP TABLE IF EXISTS forms_action CASCADE;
DROP TABLE IF EXISTS form CASCADE;
DROP TABLE IF EXISTS form_head CASCADE;
DROP TABLE IF EXISTS user_logins CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS sale_customer CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS raw_product CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS brand CASCADE;
DROP TABLE IF EXISTS setting CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS city CASCADE;
DROP TABLE IF EXISTS province CASCADE;
DROP TABLE IF EXISTS branch CASCADE;
