-- Up Migration
--
-- PHASE 13 — opening balances, and go-live. The books cannot start from zero
-- when the business does not. Opening stock is inventory with a value behind it,
-- not an account entry alone — it posts Dr inventory / Cr owner capital AND a
-- stock movement, so the stock report agrees with what is on the shelves.

CREATE TABLE opening_stock (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   integer NOT NULL REFERENCES branch(id),
    kind        text NOT NULL,
    pid         integer NOT NULL,
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    cost        numeric(18,2) NOT NULL DEFAULT 0,
    date        date NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT opening_stock_kind_check CHECK (kind IN ('RAW', 'FINISH'))
);

-- Stock movement: opening stock brings quantity in.
DROP VIEW IF EXISTS stock_movement;

CREATE VIEW stock_movement AS

SELECT 'RAW'::text AS kind, pd.pid AS pid, pd.pname AS pname, p.branch_id AS branch_id, p.date AS date,
       'PINV'::text AS source, p.id AS doc_id, pd.qty AS qty, pd.price AS price, NULL::text AS grade
FROM   purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'RAW'

UNION ALL
SELECT 'RAW', prd.pid, prd.pname, pr.branch_id, pr.date, 'PRINV', pr.id, -prd.qty, prd.price, NULL
FROM   purchase_return_detail prd JOIN purchase_return pr ON pr.id = prd.purchase_id

UNION ALL
SELECT 'RAW', pid.pid, pid.pname, i.branch_id, i.date, 'PISSUE', i.id, -pid.qty, pid.price, NULL
FROM   production_issue_detail pid JOIN production_issue i ON i.id = pid.issue_id

UNION ALL
SELECT 'RAW', os.pid, NULL, os.branch_id, os.date, 'OPEN', os.id, os.qty, os.cost, NULL
FROM   opening_stock os WHERE os.kind = 'RAW'

UNION ALL
SELECT 'FINISH', pd.pid, pd.pname, p.branch_id, p.date, 'PINV', p.id, pd.qty, pd.price, 'NEW'
FROM   purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'FINISH'

UNION ALL
SELECT 'FINISH', os.pid, NULL, os.branch_id, os.date, 'OPEN', os.id, os.qty, os.cost, 'NEW'
FROM   opening_stock os WHERE os.kind = 'FINISH'

UNION ALL
SELECT 'FINISH', o.product_id, NULL, o.branch_id, o.date, 'POUT', o.id, o.qty, o.per_unit, o.grade
FROM   production_output o

UNION ALL
SELECT 'FINISH', d.product_id, d.pname, d.branch_id, d.date, 'DAMAGE', d.id, -d.qty, d.value, NULL
FROM   damaged_stock d WHERE d.kind = 'BATTERY'

UNION ALL
SELECT 'FINISH', h.product_id, NULL, h.branch_id, h.date, 'WARRANTY', h.id, -h.qty, NULL, 'NEW'
FROM   warranty_hold h

UNION ALL
SELECT 'FINISH', wd.product_id, NULL, wc.branch_id, wc.date, 'WARRANTY', wc.id, wd.qty, NULL, wd.grade
FROM   warranty_claim_detail wd JOIN warranty_claim wc ON wc.id = wd.claim_id WHERE wd.outcome IS NOT NULL

UNION ALL
SELECT 'FINISH', wd.product_id, NULL, wc.warehouse_branch_id, wc.date, 'WARRANTY', wc.id, -wd.qty, NULL, 'NEW'
FROM   warranty_claim_detail wd JOIN warranty_claim wc ON wc.id = wd.claim_id WHERE wd.outcome = 'REPLACED_NEW'

UNION ALL
SELECT 'RAW', wp.pid, wp.pname, wc.warehouse_branch_id, wc.date, 'WARRANTY', wc.id, -wp.qty, wp.price, NULL
FROM   warranty_part wp JOIN warranty_claim wc ON wc.id = wp.claim_id

UNION ALL
SELECT 'FINISH', ed.product_id, NULL, s.branch_id, s.date, 'ESTORE', s.id, -ed.qty, ed.wholesale_price, NULL
FROM   estore_shipment_detail ed JOIN estore_shipment s ON s.id = ed.shipment_id WHERE s.status IN ('RAISED', 'ACCEPTED')

UNION ALL
SELECT 'FINISH', ed.product_id, NULL, s.branch_id, s.date, 'ESTORE', s.id, ed.qty, ed.wholesale_price, NULL
FROM   estore_shipment_detail ed JOIN estore_shipment s ON s.id = ed.shipment_id WHERE s.status = 'REJECTED'

UNION ALL
SELECT 'FINISH', sd.pid, sd.pname, s.branch_id, s.date, 'SINV', s.id, -sd.qty, sd.price, NULL
FROM   sale_detail sd JOIN sale s ON s.id = sd.sale_id WHERE sd.line_type = 'PRODUCT'

UNION ALL
SELECT 'FINISH', srd.pid, srd.pname, sr.branch_id, sr.date, 'SRINV', sr.id, srd.qty, srd.price, NULL
FROM   sale_return_detail srd JOIN sale_return sr ON sr.id = srd.sale_id

UNION ALL
SELECT COALESCE(dr.type, 'RAW'), drd.pid, drd.pname, dr.from_branch, dr.date, 'BTINV', dr.id, -drd.qty, drd.price, NULL
FROM   do_request_detail drd JOIN do_request dr ON dr.id = drd.inv_id WHERE dr.status IN ('DESPATCHED', 'RECEIVED')

UNION ALL
SELECT COALESCE(rc.type, 'RAW'), rcd.pid, rcd.pname, rc.to_branch, rc.date, 'DORINV', rc.id, rcd.qty, rcd.price, NULL
FROM   do_received_detail rcd JOIN do_received rc ON rc.id = rcd.inv_id;

COMMENT ON VIEW stock_movement IS
  'Every stock movement across all document types. qty is signed: positive in, negative out. Use (kind, pid) as the item identity — ids are not unique across the two catalogs. grade is NEW/REPAIRED for production and warranty output, NULL elsewhere.';

-- Down Migration
DROP VIEW IF EXISTS stock_movement;
-- (view is not restored here — see migration 1700000000026 for the prior shape)
DROP TABLE IF EXISTS opening_stock;
