-- Up Migration
--
-- PHASE 6 — the inter-branch account and remittance. (PLAN.md Phase 6, SPECS §7,
-- PRINCIPLES §6)
--
-- A branch answers for the stock it took. That obligation is held in one
-- inter-branch account per branch (chart group 05), mirrored by a single
-- warehouse "due from branches" account. Moving stock inside one company
-- creates no revenue; the two sides always cancel on consolidation, so the
-- combined balance sheet is never inflated by internal movement.
--
--   receipt     Dr warehouse "due from branches"  /  Cr branch "due to warehouse"
--               (branch owes more, at wholesale value received)
--   remittance  Dr branch "due to warehouse"  /  Cr branch cash
--               (warehouse side: Dr warehouse cash / Cr warehouse "due from branches")
--
-- Debt is on confirmed receipt, at wholesale (PRINCIPLES §17.6).

-- =============================================================================
-- 1. The warehouse "due from branches" account (group 05)
-- =============================================================================

INSERT INTO account (name, account_id, head_id, sub_head_id, head_code, sub_code, third, is_fixed)
SELECT 'Inter-Branch — Due from Branches', 1010502, 1, 1, 1, 1, 5, true
WHERE NOT EXISTS (SELECT 1 FROM account WHERE account_id = 1010502);

-- =============================================================================
-- 2. One "due to warehouse" account per branch, keyed back to the branch
-- =============================================================================

ALTER TABLE branch ADD COLUMN inter_branch_account integer;

-- Deterministic code: 1010502 + branch id (branch 0 and the warehouse excluded).
INSERT INTO account (name, account_id, head_id, sub_head_id, head_code, sub_code, third, is_fixed, branch_id)
SELECT 'Inter-Branch — Due to Warehouse', 1010502 + b.id, 1, 1, 1, 1, 5, true, b.id
FROM branch b
WHERE b.id > 0 AND b.type <> 'WAREHOUSE'
ON CONFLICT (account_id) DO NOTHING;

UPDATE branch b
SET inter_branch_account = a.account_id
FROM account a
WHERE a.account_id = 1010502 + b.id
  AND b.id > 0 AND b.type <> 'WAREHOUSE';

-- =============================================================================
-- 3. The remittance document
-- =============================================================================

CREATE TABLE remittance (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_number   text NOT NULL,
    date         date NOT NULL,
    from_branch  integer NOT NULL REFERENCES branch(id),
    to_branch    integer NOT NULL REFERENCES branch(id),
    amount       numeric(18,2) NOT NULL DEFAULT 0,
    method       text NOT NULL DEFAULT 'CASH',
    note         text,
    status       text NOT NULL DEFAULT 'PENDING',
    confirmed_at timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    created_by   integer NOT NULL DEFAULT 0,
    updated_by   integer NOT NULL DEFAULT 0,
    CONSTRAINT remittance_method_check CHECK (method IN ('CASH', 'BANK')),
    CONSTRAINT remittance_status_check CHECK (status IN ('PENDING', 'CONFIRMED'))
);

CREATE UNIQUE INDEX idx_remittance_doc_number ON remittance (from_branch, doc_number);

-- =============================================================================
-- 4. A new document counter type: REMITTANCE (RM)
-- =============================================================================

INSERT INTO document_counter (branch_id, doc_type)
SELECT b.id, 'REMITTANCE'
FROM branch b
WHERE b.id > 0
ON CONFLICT (branch_id, doc_type) DO NOTHING;

DROP TRIGGER IF EXISTS trg_document_counter_from_branch ON branch;
DROP FUNCTION IF EXISTS document_counter_fanout_from_branch();

CREATE FUNCTION document_counter_fanout_from_branch() RETURNS trigger
LANGUAGE plpgsql AS $fanout_branch$
BEGIN
    IF NEW.id = 0 OR NOT NEW.is_active THEN
        RETURN NEW;
    END IF;

    INSERT INTO document_counter (branch_id, doc_type)
    SELECT NEW.id, t.doc_type
    FROM (VALUES
        ('SALE_WALKIN'), ('SALE_CREDIT'), ('SALE_RETURN'),
        ('PURCHASE'), ('PURCHASE_RETURN'), ('HOLD_SALE'),
        ('PRODUCTION'), ('DEMAND_ORDER'), ('LAB'), ('LAB_RECEIVED'),
        ('DISPATCH'), ('RECEIPT'), ('REMITTANCE')
    ) AS t(doc_type)
    ON CONFLICT (branch_id, doc_type) DO NOTHING;

    RETURN NEW;
END;
$fanout_branch$;

CREATE TRIGGER trg_document_counter_from_branch
    AFTER INSERT OR UPDATE OF is_active ON branch
    FOR EACH ROW EXECUTE FUNCTION document_counter_fanout_from_branch();

-- =============================================================================
-- 5. Permission for the Remittance screen (form 55 / code 511, under head 5)
-- =============================================================================

INSERT INTO form (id, head_id, form_name, sub, sr, ids, form_code)
VALUES (55, 5, 'Remittance', NULL, 3, 55, 511)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('form', 'id'), GREATEST((SELECT MAX(id) FROM form), 1));

INSERT INTO forms_action (form_id, action_name, sr, action_code)
SELECT 55, a.name, a.seq, 5110 + a.seq
FROM (VALUES ('View', 1), ('New', 2), ('Confirm', 3)) AS a(name, seq)
WHERE NOT EXISTS (SELECT 1 FROM forms_action WHERE form_id = 55 AND action_code = 5110 + a.seq);

-- Down Migration
DROP TRIGGER IF EXISTS trg_document_counter_from_branch ON branch;
DROP FUNCTION IF EXISTS document_counter_fanout_from_branch();

CREATE FUNCTION document_counter_fanout_from_branch() RETURNS trigger
LANGUAGE plpgsql AS $fanout_branch$
BEGIN
    IF NEW.id = 0 OR NOT NEW.is_active THEN
        RETURN NEW;
    END IF;

    INSERT INTO document_counter (branch_id, doc_type)
    SELECT NEW.id, t.doc_type
    FROM (VALUES
        ('SALE_WALKIN'), ('SALE_CREDIT'), ('SALE_RETURN'),
        ('PURCHASE'), ('PURCHASE_RETURN'), ('HOLD_SALE'),
        ('PRODUCTION'), ('DEMAND_ORDER'), ('LAB'), ('LAB_RECEIVED'),
        ('DISPATCH'), ('RECEIPT')
    ) AS t(doc_type)
    ON CONFLICT (branch_id, doc_type) DO NOTHING;

    RETURN NEW;
END;
$fanout_branch$;

CREATE TRIGGER trg_document_counter_from_branch
    AFTER INSERT OR UPDATE OF is_active ON branch
    FOR EACH ROW EXECUTE FUNCTION document_counter_fanout_from_branch();

DELETE FROM document_counter WHERE doc_type = 'REMITTANCE';
DROP TABLE IF EXISTS remittance;
ALTER TABLE branch DROP COLUMN IF EXISTS inter_branch_account;
DELETE FROM account WHERE account_id >= 1010502 AND name LIKE 'Inter-Branch%';

DELETE FROM role_assign WHERE form_id = 55;
DELETE FROM forms_action WHERE form_id = 55;
DELETE FROM form WHERE id = 55;
