-- Up Migration
--
-- Notifications — the bell in the top bar. One row per event a branch (or the
-- warehouse) needs to see: a new demand order, a dispatch, a receipt, a
-- remittance. A branch sees its own; the super admin sees everything.

CREATE TABLE notification (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   integer NOT NULL REFERENCES branch(id),
    type        text NOT NULL DEFAULT 'DEMAND',
    title       text NOT NULL,
    body        text,
    link        text,
    is_read     boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX notification_branch_idx ON notification (branch_id, is_read, created_at DESC);

-- Down Migration
DROP TABLE IF EXISTS notification;
