-- Up Migration
--
-- Stock adjustment — a physical-count correction. The super admin increases or
-- decreases a branch's on-hand for one product, posting a balanced journal and
-- a signed stock movement. This is the "increase / decrease" the owner asked
-- for on top of the document-driven movement (PRINCIPLES §6: stock moves only
-- through a document — this is that document).

-- 1. The balancing account (head 5 / cost of sales). One account nets shrinkage
--    (Dr) against surplus (Cr), so the income statement shows the true cost.
INSERT INTO account (name, account_id, head_id, sub_head_id, head_code, sub_code, third_code, is_fixed)
SELECT 'Stock Adjustment', 5010105, 5, 8, 5, 1, 1, true
WHERE NOT EXISTS (SELECT 1 FROM account WHERE account_id = 5010105);

-- 2. The document.
CREATE TABLE stock_adjustment (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_number text NOT NULL,
    branch_id  integer NOT NULL REFERENCES branch(id),
    date       date NOT NULL,
    kind       text NOT NULL,
    reason     text NOT NULL,
    note       text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 0,
    updated_by integer NOT NULL DEFAULT 0,
    CONSTRAINT stock_adjustment_kind_check CHECK (kind IN ('RAW', 'FINISH'))
);

CREATE UNIQUE INDEX idx_stock_adjustment_doc_number ON stock_adjustment (branch_id, doc_number);

CREATE TABLE stock_adjustment_detail (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adj_id integer NOT NULL REFERENCES stock_adjustment(id) ON DELETE CASCADE,
    pid    integer NOT NULL,
    pname  text,
    qty    numeric(18,3) NOT NULL,  -- signed: positive = increase, negative = decrease
    price  numeric(18,2) NOT NULL,  -- unit cost
    total  numeric(18,2) NOT NULL
);

-- 3. Document counter type (ADJ) + fan-out trigger refresh.
INSERT INTO document_counter (branch_id, doc_type)
SELECT b.id, 'ADJUSTMENT' FROM branch b WHERE b.id > 0
ON CONFLICT (branch_id, doc_type) DO NOTHING;

DROP TRIGGER IF EXISTS trg_document_counter_from_branch ON branch;
DROP FUNCTION IF EXISTS document_counter_fanout_from_branch();
CREATE FUNCTION document_counter_fanout_from_branch() RETURNS trigger
LANGUAGE plpgsql AS $fanout_branch$
BEGIN
    IF NEW.id = 0 OR NOT NEW.is_active THEN
        RETURN NEW;
    END IF;

    INSERT INTO document_counter (branch_id, doc_type)
    SELECT NEW.id, t.doc_type
    FROM (VALUES
        ('SALE_WALKIN'), ('SALE_CREDIT'), ('SALE_RETURN'),
        ('PURCHASE'), ('PURCHASE_RETURN'), ('HOLD_SALE'),
        ('PRODUCTION'), ('DEMAND_ORDER'), ('LAB'), ('LAB_RECEIVED'),
        ('DISPATCH'), ('RECEIPT'), ('REMITTANCE'), ('WARRANTY'), ('ESTORE'),
        ('ADJUSTMENT')
    ) AS t(doc_type)
    ON CONFLICT (branch_id, doc_type) DO NOTHING;

    RETURN NEW;
END;
$fanout_branch$;

CREATE TRIGGER trg_document_counter_from_branch
    AFTER INSERT OR UPDATE OF is_active ON branch
    FOR EACH ROW EXECUTE FUNCTION document_counter_fanout_from_branch();

-- 4. Stock movement — the signed adjustment lands in the unified view.
DROP VIEW IF EXISTS stock_movement;

CREATE VIEW stock_movement AS

SELECT 'RAW'::text AS kind, pd.pid AS pid, pd.pname AS pname, p.branch_id AS branch_id, p.date AS date,
       'PINV'::text AS source, p.id AS doc_id, pd.qty AS qty, pd.price AS price, NULL::text AS grade
FROM   purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'RAW'

UNION ALL
SELECT 'RAW', prd.pid, prd.pname, pr.branch_id, pr.date, 'PRINV', pr.id, -prd.qty, prd.price, NULL
FROM   purchase_return_detail prd JOIN purchase_return pr ON pr.id = prd.purchase_id

UNION ALL
SELECT 'RAW', pid.pid, pid.pname, i.branch_id, i.date, 'PISSUE', i.id, -pid.qty, pid.price, NULL
FROM   production_issue_detail pid JOIN production_issue i ON i.id = pid.issue_id

UNION ALL
SELECT 'RAW', os.pid, NULL, os.branch_id, os.date, 'OPEN', os.id, os.qty, os.cost, NULL
FROM   opening_stock os WHERE os.kind = 'RAW'

UNION ALL
SELECT 'FINISH', pd.pid, pd.pname, p.branch_id, p.date, 'PINV', p.id, pd.qty, pd.price, 'NEW'
FROM   purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'FINISH'

UNION ALL
SELECT 'FINISH', os.pid, NULL, os.branch_id, os.date, 'OPEN', os.id, os.qty, os.cost, 'NEW'
FROM   opening_stock os WHERE os.kind = 'FINISH'

UNION ALL
SELECT 'FINISH', o.product_id, NULL, o.branch_id, o.date, 'POUT', o.id, o.qty, o.per_unit, o.grade
FROM   production_output o

UNION ALL
SELECT 'FINISH', d.product_id, d.pname, d.branch_id, d.date, 'DAMAGE', d.id, -d.qty, d.value, NULL
FROM   damaged_stock d WHERE d.kind = 'BATTERY'

UNION ALL
SELECT 'FINISH', h.product_id, NULL, h.branch_id, h.date, 'WARRANTY', h.id, -h.qty, NULL, 'NEW'
FROM   warranty_hold h

UNION ALL
SELECT 'FINISH', wd.product_id, NULL, wc.branch_id, wc.date, 'WARRANTY', wc.id, wd.qty, NULL, wd.grade
FROM   warranty_claim_detail wd JOIN warranty_claim wc ON wc.id = wd.claim_id WHERE wd.outcome IS NOT NULL

UNION ALL
SELECT 'FINISH', wd.product_id, NULL, wc.warehouse_branch_id, wc.date, 'WARRANTY', wc.id, -wd.qty, NULL, 'NEW'
FROM   warranty_claim_detail wd JOIN warranty_claim wc ON wc.id = wd.claim_id WHERE wd.outcome = 'REPLACED_NEW'

UNION ALL
SELECT 'RAW', wp.pid, wp.pname, wc.warehouse_branch_id, wc.date, 'WARRANTY', wc.id, -wp.qty, wp.price, NULL
FROM   warranty_part wp JOIN warranty_claim wc ON wc.id = wp.claim_id

UNION ALL
SELECT 'FINISH', ed.product_id, NULL, s.branch_id, s.date, 'ESTORE', s.id, -ed.qty, ed.wholesale_price, NULL
FROM   estore_shipment_detail ed JOIN estore_shipment s ON s.id = ed.shipment_id WHERE s.status IN ('RAISED', 'ACCEPTED')

UNION ALL
SELECT 'FINISH', ed.product_id, NULL, s.branch_id, s.date, 'ESTORE', s.id, ed.qty, ed.wholesale_price, NULL
FROM   estore_shipment_detail ed JOIN estore_shipment s ON s.id = ed.shipment_id WHERE s.status = 'REJECTED'

UNION ALL
SELECT 'FINISH', sd.pid, sd.pname, s.branch_id, s.date, 'SINV', s.id, -sd.qty, sd.price, NULL
FROM   sale_detail sd JOIN sale s ON s.id = sd.sale_id WHERE sd.line_type = 'PRODUCT'

UNION ALL
SELECT 'FINISH', srd.pid, srd.pname, sr.branch_id, sr.date, 'SRINV', sr.id, srd.qty, srd.price, NULL
FROM   sale_return_detail srd JOIN sale_return sr ON sr.id = srd.sale_id

UNION ALL
SELECT COALESCE(dr.type, 'RAW'), drd.pid, drd.pname, dr.from_branch, dr.date, 'BTINV', dr.id, -drd.qty, drd.price, NULL
FROM   do_request_detail drd JOIN do_request dr ON dr.id = drd.inv_id WHERE dr.status IN ('DESPATCHED', 'RECEIVED')

UNION ALL
SELECT COALESCE(rc.type, 'RAW'), rcd.pid, rcd.pname, rc.to_branch, rc.date, 'DORINV', rc.id, rcd.qty, rcd.price, NULL
FROM   do_received_detail rcd JOIN do_received rc ON rc.id = rcd.inv_id

UNION ALL
SELECT COALESCE(a.kind, 'RAW'), ad.pid, ad.pname, a.branch_id, a.date, 'ADJUST', a.id, ad.qty, ad.price, NULL
FROM   stock_adjustment_detail ad JOIN stock_adjustment a ON a.id = ad.adj_id;

COMMENT ON VIEW stock_movement IS
  'Every stock movement across all document types. qty is signed: positive in, negative out. Use (kind, pid) as the item identity — ids are not unique across the two catalogs. grade is NEW/REPAIRED for production and warranty output, NULL elsewhere.';

-- 5. Screen permission (form 58 / code 513, under head 10 — Production).
INSERT INTO form (id, head_id, form_name, sub, sr, ids, form_code)
VALUES (58, 10, 'Stock Adjustment', NULL, 2, 58, 513)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('form', 'id'), GREATEST((SELECT MAX(id) FROM form), 1));

INSERT INTO forms_action (form_id, action_name, sr, action_code)
SELECT 58, a.name, a.seq, 5130 + a.seq
FROM (VALUES ('View', 1), ('New', 2), ('Edit', 3), ('Delete', 4)) AS a(name, seq)
WHERE NOT EXISTS (SELECT 1 FROM forms_action WHERE form_id = 58 AND action_code = 5130 + a.seq);

-- Down Migration
DROP VIEW IF EXISTS stock_movement;
-- (view not restored here — see migration 1700000000027 for the prior shape)
DROP TRIGGER IF EXISTS trg_document_counter_from_branch ON branch;
DROP FUNCTION IF EXISTS document_counter_fanout_from_branch();
DROP TABLE IF EXISTS stock_adjustment_detail;
DROP TABLE IF EXISTS stock_adjustment;
DELETE FROM document_counter WHERE doc_type = 'ADJUSTMENT';
DELETE FROM forms_action WHERE form_id = 58;
DELETE FROM form WHERE id = 58;
DELETE FROM account WHERE account_id = 5010105;
