-- Up Migration
--
-- Phase 0 groundwork (PLAN.md) — drop province, city and department.
--
-- These are legacy reference tables this business never uses, reconstructed
-- from the ASP.NET model classes along with everything else. `province` and
-- `city` have never been queried anywhere in this codebase — only the plain
-- TEXT columns of the same name on supplier/employee/customer are used, and
-- those stay untouched. `department` is queried (the employee form's
-- dropdown), so its one reference goes with it.
--
-- Not a "nothing is deleted that has history" violation (ground rule 6):
-- these are empty, unused lookup tables, not transactional history.

ALTER TABLE employee DROP COLUMN department_id;

DROP TABLE department;
DROP TABLE city;
DROP TABLE province;

-- Down Migration
CREATE TABLE province (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE city (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE department (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

ALTER TABLE employee ADD COLUMN department_id integer REFERENCES department(id);
