-- Up Migration
--
-- Branch 0 — the "All Branches" sentinel.
--
-- The legacy system used branch_id = 0 to mean "not scoped to any one branch":
-- a super admin logs in with BranchId 0 and sees every branch
-- (`_userId == 0 && _branchId == 0 && isSuperAdmin`). That convention is
-- preserved so existing rows and role assignments keep their meaning.
--
-- Because this rewrite adds real foreign keys — which the legacy schema lacked
-- entirely — every `branch_id integer NOT NULL DEFAULT 0 REFERENCES branch(id)`
-- column needs a branch row with id 0 to point at. Without it, inserting a
-- super-admin login or any DEFAULT-0 row fails on the FK.
--
-- This row is infrastructure, not a real location. Never show it in a branch
-- picker; filter with `WHERE id > 0`.

INSERT INTO branch (id, name, address)
VALUES (0, 'All Branches', 'Sentinel row — not a physical branch')
ON CONFLICT (id) DO NOTHING;

-- `id` is GENERATED BY DEFAULT AS IDENTITY, so explicit inserts do not advance
-- the sequence. Re-align it or the first generated branch would collide.
SELECT setval(
    pg_get_serial_sequence('branch', 'id'),
    GREATEST((SELECT MAX(id) FROM branch), 1)
);

-- Down Migration
DELETE FROM branch WHERE id = 0;
