-- Up Migration
--
-- PHASE 4 — production. (PLAN.md Phase 4, SPECS §5, PRINCIPLES §4)
--
-- The old `production` table — one header with labour/electricity/other
-- conversion costs — did not model issue-to-worker, work in progress, damage or
-- rework, and its posting credited cash/inter-branch for a conversion cost that
-- PRINCIPLES §4 explicitly removes ("there is no pay system, so no rate exists
-- to read"). It is replaced wholesale.
--
-- The new model:
--
--   worker               name, phone, active — no pay system
--   production_issue     a cart of raw parts issued to a named worker (WIP)
--   production_issue_detail  the parts in that cart
--   production_output    the READY batteries that came back (grade NEW/REPAIRED)
--   used_stock           parts consumed into the batteries
--   damaged_stock        parts AND finished batteries spoiled (no ledger)
--   rework               a finished battery sent back to a worker
--
-- Cost: production cost = complete set + cells + other parts (material only).
-- Damaged material is absorbed into the surviving batteries, so the ledger
-- stays balanced without a damage leg (decision, PRINCIPLES §17.16 style).
--
-- Grade enters here: the movement view gains a `grade` column; everything the
-- warehouse produces is NEW, a repaired battery is REPAIRED.

-- =============================================================================
-- 1. Worker
-- =============================================================================

CREATE TABLE worker (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    phone       text,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

-- =============================================================================
-- 2. Issue — the cart, raw parts to a worker
-- =============================================================================

CREATE TABLE production_issue (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_number  text NOT NULL,
    date        date NOT NULL,
    worker_id   integer NOT NULL REFERENCES worker(id),
    branch_id   integer NOT NULL REFERENCES branch(id),
    note        text,
    status      text NOT NULL DEFAULT 'OPEN',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT production_issue_status_check CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE UNIQUE INDEX idx_production_issue_doc_number ON production_issue (branch_id, doc_number);

CREATE TABLE production_issue_detail (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id  integer NOT NULL REFERENCES production_issue(id) ON DELETE CASCADE,
    pid       integer NOT NULL,
    pname     text,
    qty       numeric(18,3) NOT NULL DEFAULT 0,
    price     numeric(18,2) NOT NULL DEFAULT 0,
    total     numeric(18,2) NOT NULL DEFAULT 0,
    status    text NOT NULL DEFAULT 'ISSUED',
    CONSTRAINT production_issue_detail_status_check
        CHECK (status IN ('ISSUED', 'USED', 'DAMAGED'))
);

-- =============================================================================
-- 3. Output — the batteries that came back
-- =============================================================================

CREATE TABLE production_output (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date NOT NULL,
    issue_id    integer REFERENCES production_issue(id),
    worker_id   integer NOT NULL REFERENCES worker(id),
    product_id  integer NOT NULL REFERENCES product(id),
    branch_id   integer NOT NULL REFERENCES branch(id),
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    per_unit    numeric(18,2) NOT NULL DEFAULT 0,
    total_cost  numeric(18,2) NOT NULL DEFAULT 0,
    grade       text NOT NULL DEFAULT 'NEW',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT production_output_grade_check CHECK (grade IN ('NEW', 'REPAIRED'))
);

-- =============================================================================
-- 4. Used stock — parts consumed into the batteries
-- =============================================================================

CREATE TABLE used_stock (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id    integer REFERENCES production_issue(id),
    output_id   integer REFERENCES production_output(id),
    pid         integer NOT NULL,
    pname       text,
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    price       numeric(18,2) NOT NULL DEFAULT 0,
    total       numeric(18,2) NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- =============================================================================
-- 5. Damaged stock — parts AND finished batteries, no ledger
-- =============================================================================

CREATE TABLE damaged_stock (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date NOT NULL,
    worker_id   integer REFERENCES worker(id),
    branch_id   integer NOT NULL REFERENCES branch(id),
    issue_id    integer REFERENCES production_issue(id),
    kind        text NOT NULL DEFAULT 'PART',
    pid         integer,
    product_id  integer REFERENCES product(id),
    pname       text,
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    value       numeric(18,2) NOT NULL DEFAULT 0,
    reason      text,
    status      text NOT NULL DEFAULT 'DAMAGED',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT damaged_stock_kind_check   CHECK (kind IN ('PART', 'BATTERY')),
    CONSTRAINT damaged_stock_status_check CHECK (status IN ('DAMAGED', 'RESTOCKED', 'REPAIRED'))
);

-- =============================================================================
-- 6. Rework — a finished battery back to a worker
-- =============================================================================

CREATE TABLE rework (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date NOT NULL,
    product_id  integer NOT NULL REFERENCES product(id),
    worker_id   integer NOT NULL REFERENCES worker(id),
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    note        text,
    status      text NOT NULL DEFAULT 'OPEN',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT rework_status_check CHECK (status IN ('OPEN', 'DONE'))
);

-- =============================================================================
-- 7. Purchase — raw or finished goods
--
-- The warehouse also BUYS finished goods (chargers, adapters) and dispatches
-- them like batteries; for those the purchase cost stands in for production
-- cost (PRINCIPLES §17.16). `kind` discriminates which catalog a purchase line
-- references: raw_product, or product (finished).
-- =============================================================================

ALTER TABLE purchase
    ADD COLUMN kind text NOT NULL DEFAULT 'RAW';

ALTER TABLE purchase
    ADD CONSTRAINT purchase_kind_check CHECK (kind IN ('RAW', 'FINISH'));

-- =============================================================================
-- 8. Rebuild the movement view with grade and the new sources
-- =============================================================================

DROP VIEW IF EXISTS stock_movement;

CREATE VIEW stock_movement AS

-- ---------------------------------------------------------------------------
-- RAW materials
-- ---------------------------------------------------------------------------

-- Purchases bring raw stock in.
SELECT 'RAW'::text        AS kind,
       pd.pid             AS pid,
       pd.pname           AS pname,
       p.branch_id        AS branch_id,
       p.date             AS date,
       'PINV'::text       AS source,
       p.id               AS doc_id,
       pd.qty             AS qty,
       pd.price           AS price,
       NULL::text         AS grade
FROM   purchase_detail pd
JOIN   purchase p ON p.id = pd.purchase_id
WHERE  p.kind = 'RAW'

UNION ALL

-- Purchase returns send raw stock back.
SELECT 'RAW', prd.pid, prd.pname, pr.branch_id, pr.date, 'PRINV', pr.id,
       -prd.qty, prd.price, NULL
FROM   purchase_return_detail prd
JOIN   purchase_return pr ON pr.id = prd.purchase_id

UNION ALL

-- Issuing a cart moves raw parts out of stock into work in progress.
SELECT 'RAW', pid.pid, pid.pname, i.branch_id, i.date, 'PISSUE', i.id,
       -pid.qty, pid.price, NULL
FROM   production_issue_detail pid
JOIN   production_issue i ON i.id = pid.issue_id

-- ---------------------------------------------------------------------------
-- FINISHED goods
-- ---------------------------------------------------------------------------

UNION ALL

-- Buying finished goods (chargers etc.) brings them in.
SELECT 'FINISH', pd.pid, pd.pname, p.branch_id, p.date, 'PINV', p.id,
       pd.qty, pd.price, 'NEW'
FROM   purchase_detail pd
JOIN   purchase p ON p.id = pd.purchase_id
WHERE  p.kind = 'FINISH'

UNION ALL

-- Production output: the batteries that came back, with their grade.
SELECT 'FINISH', o.product_id, NULL, o.branch_id, o.date, 'POUT', o.id,
       o.qty, o.per_unit, o.grade
FROM   production_output o

UNION ALL

-- A finished battery marked damaged leaves ready stock.
SELECT 'FINISH', d.product_id, d.pname, d.branch_id, d.date, 'DAMAGE', d.id,
       -d.qty, d.value, NULL
FROM   damaged_stock d
WHERE  d.kind = 'BATTERY'

UNION ALL

-- Sales issue finished goods.
SELECT 'FINISH', sd.pid, sd.pname, s.branch_id, s.date, 'SINV', s.id,
       -sd.qty, sd.price, NULL
FROM   sale_detail sd
JOIN   sale s ON s.id = sd.sale_id

UNION ALL

-- Sale returns bring them back.
SELECT 'FINISH', srd.pid, srd.pname, sr.branch_id, sr.date, 'SRINV', sr.id,
       srd.qty, srd.price, NULL
FROM   sale_return_detail srd
JOIN   sale_return sr ON sr.id = srd.sale_id

-- ---------------------------------------------------------------------------
-- Inter-branch transfers move EITHER kind
-- ---------------------------------------------------------------------------

UNION ALL

SELECT COALESCE(dr.type, 'RAW'), drd.pid, drd.pname, dr.from_branch, dr.date,
       'BTINV', dr.id, -drd.qty, drd.price, NULL
FROM   do_request_detail drd
JOIN   do_request dr ON dr.id = drd.inv_id
WHERE  dr.status IN ('DESPATCHED', 'RECEIVED')

UNION ALL

SELECT COALESCE(rc.type, 'RAW'), rcd.pid, rcd.pname, rc.to_branch, rc.date,
       'DORINV', rc.id, rcd.qty, rcd.price, NULL
FROM   do_received_detail rcd
JOIN   do_received rc ON rc.id = rcd.inv_id;

COMMENT ON VIEW stock_movement IS
  'Every stock movement across all document types. qty is signed: positive in, negative out. Use (kind, pid) as the item identity — ids are not unique across the two catalogs. grade is NEW/REPAIRED for production output, NULL elsewhere.';

-- Down Migration
--
-- The old production table is gone; this down migration cannot faithfully
-- restore it. It recreates a placeholder `production` table (no data) so a
-- rollback does not leave dependent code pointing at nothing.

DROP VIEW IF EXISTS stock_movement;

ALTER TABLE purchase
    DROP CONSTRAINT IF EXISTS purchase_kind_check,
    DROP COLUMN IF EXISTS kind;

DROP TABLE IF EXISTS rework;
DROP TABLE IF EXISTS damaged_stock;
DROP TABLE IF EXISTS used_stock;
DROP TABLE IF EXISTS production_output;
DROP TABLE IF EXISTS production_issue_detail;
DROP TABLE IF EXISTS production_issue;
DROP TABLE IF EXISTS worker;

CREATE TABLE production (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          date NOT NULL,
    doc_number    text,
    branch_id     integer NOT NULL REFERENCES branch(id),
    pid           integer NOT NULL,
    qty           integer NOT NULL DEFAULT 0,
    note          text,
    labor_cost    numeric(18,2) NOT NULL DEFAULT 0,
    electric_cost numeric(18,2) NOT NULL DEFAULT 0,
    other_cost    numeric(18,2) NOT NULL DEFAULT 0,
    material_cost numeric(18,2) NOT NULL DEFAULT 0,
    extra         numeric(18,2) NOT NULL DEFAULT 0,
    extra1        numeric(18,2) NOT NULL DEFAULT 0,
    per_unit      numeric(18,2) NOT NULL DEFAULT 0,
    total_cost    numeric(18,2) NOT NULL DEFAULT 0,
    gross_total   numeric(18,2) NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    created_by    integer NOT NULL DEFAULT 0,
    updated_by    integer NOT NULL DEFAULT 0
);

CREATE TABLE production_detail (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_id   integer NOT NULL REFERENCES production(id) ON DELETE CASCADE,
    pid      integer NOT NULL,
    pname    text,
    price    numeric(18,2) NOT NULL DEFAULT 0,
    qty      numeric(18,3) NOT NULL DEFAULT 0,
    total    numeric(18,2) NOT NULL DEFAULT 0
);
