-- Up Migration
--
-- PHASE 9 — warranty. (PLAN.md Phase 9, SPECS §10, PRINCIPLES §8)
--
-- The customer never waits: the branch hands over a replacement from its own
-- stock immediately, the faulty unit sits in Warranty Hold (not sellable), and
-- the branch raises a claim the warehouse assesses. The branch is never charged;
-- the warehouse carries the cost as a warranty expense. Either outcome returns
-- to the branch that claimed it, graded Repaired (same unit) or New (a new
-- battery), restoring branch stock.

-- =============================================================================
-- 1. Warranty hold — faulty units at a branch, not sellable, not in stock value
-- =============================================================================

CREATE TABLE warranty_hold (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   integer NOT NULL REFERENCES branch(id),
    product_id  integer NOT NULL REFERENCES product(id),
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    date        date NOT NULL,
    note        text,
    status      text NOT NULL DEFAULT 'HELD',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT warranty_hold_status_check CHECK (status IN ('HELD', 'CLAIMED'))
);

-- =============================================================================
-- 2. Warranty claim — branch -> warehouse
-- =============================================================================

CREATE TABLE warranty_claim (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_number  text NOT NULL,
    branch_id   integer NOT NULL REFERENCES branch(id),
    warehouse_branch_id integer REFERENCES branch(id),
    date        date NOT NULL,
    status      text NOT NULL DEFAULT 'RAISED',
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT warranty_claim_status_check
        CHECK (status IN ('RAISED', 'ASSESSED', 'CLOSED'))
);

CREATE UNIQUE INDEX idx_warranty_claim_doc_number ON warranty_claim (branch_id, doc_number);

CREATE TABLE warranty_claim_detail (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id    integer NOT NULL REFERENCES warranty_claim(id) ON DELETE CASCADE,
    product_id  integer NOT NULL REFERENCES product(id),
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    assessment  text,
    outcome     text,
    grade       text,
    CONSTRAINT warranty_claim_detail_assessment_check
        CHECK (assessment IS NULL OR assessment IN ('REPAIRABLE', 'NOT_REPAIRABLE')),
    CONSTRAINT warranty_claim_detail_outcome_check
        CHECK (outcome IS NULL OR outcome IN ('RETURNED_REPAIRED', 'REPLACED_NEW'))
);

-- Raw parts consumed repairing a claimed unit.
CREATE TABLE warranty_part (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id    integer NOT NULL REFERENCES warranty_claim(id) ON DELETE CASCADE,
    pid         integer NOT NULL,
    pname       text,
    qty         numeric(18,3) NOT NULL DEFAULT 0,
    price       numeric(18,2) NOT NULL DEFAULT 0,
    total       numeric(18,2) NOT NULL DEFAULT 0
);

-- =============================================================================
-- 3. Warranty expense account (head 5, cost of sales)
-- =============================================================================

INSERT INTO account (name, account_id, head_id, sub_head_id, head_code, sub_code, third, is_fixed)
SELECT 'Warranty Expense', 5010104, 5, 8, 5, 1, 4, true
WHERE NOT EXISTS (SELECT 1 FROM account WHERE account_id = 5010104);

-- =============================================================================
-- 4. A new document counter type: WARRANTY (WC)
-- =============================================================================

INSERT INTO document_counter (branch_id, doc_type)
SELECT b.id, 'WARRANTY' FROM branch b WHERE b.id > 0
ON CONFLICT (branch_id, doc_type) DO NOTHING;

-- Recreate the fan-out trigger so a branch created later also gets WARRANTY.
DROP TRIGGER IF EXISTS trg_document_counter_from_branch ON branch;
DROP FUNCTION IF EXISTS document_counter_fanout_from_branch();

CREATE FUNCTION document_counter_fanout_from_branch() RETURNS trigger
LANGUAGE plpgsql AS $fanout_branch$
BEGIN
    IF NEW.id = 0 OR NOT NEW.is_active THEN
        RETURN NEW;
    END IF;

    INSERT INTO document_counter (branch_id, doc_type)
    SELECT NEW.id, t.doc_type
    FROM (VALUES
        ('SALE_WALKIN'), ('SALE_CREDIT'), ('SALE_RETURN'),
        ('PURCHASE'), ('PURCHASE_RETURN'), ('HOLD_SALE'),
        ('PRODUCTION'), ('DEMAND_ORDER'), ('LAB'), ('LAB_RECEIVED'),
        ('DISPATCH'), ('RECEIPT'), ('REMITTANCE'), ('WARRANTY')
    ) AS t(doc_type)
    ON CONFLICT (branch_id, doc_type) DO NOTHING;

    RETURN NEW;
END;
$fanout_branch$;

CREATE TRIGGER trg_document_counter_from_branch
    AFTER INSERT OR UPDATE OF is_active ON branch
    FOR EACH ROW EXECUTE FUNCTION document_counter_fanout_from_branch();

-- =============================================================================
-- 5. Stock movement — the warranty exchange
-- =============================================================================

DROP VIEW IF EXISTS stock_movement;

CREATE VIEW stock_movement AS

SELECT 'RAW'::text AS kind,
       pd.pid AS pid,
       pd.pname AS pname,
       p.branch_id AS branch_id,
       p.date AS date,
       'PINV'::text AS source,
       p.id AS doc_id,
       pd.qty AS qty,
       pd.price AS price,
       NULL::text AS grade
FROM   purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'RAW'

UNION ALL
SELECT 'RAW', prd.pid, prd.pname, pr.branch_id, pr.date, 'PRINV', pr.id, -prd.qty, prd.price, NULL
FROM   purchase_return_detail prd JOIN purchase_return pr ON pr.id = prd.purchase_id

UNION ALL
SELECT 'RAW', pid.pid, pid.pname, i.branch_id, i.date, 'PISSUE', i.id, -pid.qty, pid.price, NULL
FROM   production_issue_detail pid JOIN production_issue i ON i.id = pid.issue_id

UNION ALL
SELECT 'FINISH', pd.pid, pd.pname, p.branch_id, p.date, 'PINV', p.id, pd.qty, pd.price, 'NEW'
FROM   purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'FINISH'

UNION ALL
SELECT 'FINISH', o.product_id, NULL, o.branch_id, o.date, 'POUT', o.id, o.qty, o.per_unit, o.grade
FROM   production_output o

UNION ALL
SELECT 'FINISH', d.product_id, d.pname, d.branch_id, d.date, 'DAMAGE', d.id, -d.qty, d.value, NULL
FROM   damaged_stock d WHERE d.kind = 'BATTERY'

UNION ALL
-- Warranty: the branch hands over a replacement (finished out at the branch).
SELECT 'FINISH', h.product_id, NULL, h.branch_id, h.date, 'WARRANTY', h.id, -h.qty, NULL, 'NEW'
FROM   warranty_hold h

UNION ALL
-- Warranty resolution: the replacement/repaired unit returns to the branch.
SELECT 'FINISH', wd.product_id, NULL, wc.branch_id, wc.date, 'WARRANTY', wc.id, wd.qty, NULL, wd.grade
FROM   warranty_claim_detail wd JOIN warranty_claim wc ON wc.id = wd.claim_id
WHERE  wd.outcome IS NOT NULL

UNION ALL
-- A not-repairable claim issues a new battery from the warehouse's ready stock.
SELECT 'FINISH', wd.product_id, NULL, wc.warehouse_branch_id, wc.date, 'WARRANTY', wc.id, -wd.qty, NULL, 'NEW'
FROM   warranty_claim_detail wd JOIN warranty_claim wc ON wc.id = wd.claim_id
WHERE  wd.outcome = 'REPLACED_NEW'

UNION ALL
-- Warranty repair consumes raw parts at the warehouse.
SELECT 'RAW', wp.pid, wp.pname, wc.warehouse_branch_id, wc.date, 'WARRANTY', wc.id, -wp.qty, wp.price, NULL
FROM   warranty_part wp JOIN warranty_claim wc ON wc.id = wp.claim_id

UNION ALL
SELECT 'FINISH', sd.pid, sd.pname, s.branch_id, s.date, 'SINV', s.id, -sd.qty, sd.price, NULL
FROM   sale_detail sd JOIN sale s ON s.id = sd.sale_id WHERE sd.line_type = 'PRODUCT'

UNION ALL
SELECT 'FINISH', srd.pid, srd.pname, sr.branch_id, sr.date, 'SRINV', sr.id, srd.qty, srd.price, NULL
FROM   sale_return_detail srd JOIN sale_return sr ON sr.id = srd.sale_id

UNION ALL
SELECT COALESCE(dr.type, 'RAW'), drd.pid, drd.pname, dr.from_branch, dr.date, 'BTINV', dr.id, -drd.qty, drd.price, NULL
FROM   do_request_detail drd JOIN do_request dr ON dr.id = drd.inv_id WHERE dr.status IN ('DESPATCHED', 'RECEIVED')

UNION ALL
SELECT COALESCE(rc.type, 'RAW'), rcd.pid, rcd.pname, rc.to_branch, rc.date, 'DORINV', rc.id, rcd.qty, rcd.price, NULL
FROM   do_received_detail rcd JOIN do_received rc ON rc.id = rcd.inv_id;

COMMENT ON VIEW stock_movement IS
  'Every stock movement across all document types. qty is signed: positive in, negative out. Use (kind, pid) as the item identity — ids are not unique across the two catalogs. grade is NEW/REPAIRED for production and warranty output, NULL elsewhere.';

-- =============================================================================
-- 6. Warranty screen permission (form 57 / code 512, under head 5)
-- =============================================================================

INSERT INTO form (id, head_id, form_name, sub, sr, ids, form_code)
VALUES (57, 5, 'Warranty', NULL, 4, 57, 512)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('form', 'id'), GREATEST((SELECT MAX(id) FROM form), 1));

INSERT INTO forms_action (form_id, action_name, sr, action_code)
SELECT 57, a.name, a.seq, 5120 + a.seq
FROM (VALUES ('View', 1), ('New', 2), ('Edit', 3)) AS a(name, seq)
WHERE NOT EXISTS (SELECT 1 FROM forms_action WHERE form_id = 57 AND action_code = 5120 + a.seq);

-- Down Migration
DROP VIEW IF EXISTS stock_movement;
-- (view rebuilt from the previous shape in migration 020/021 is not restored here;
--  see those migrations' down for the prior source list — a rollback past Phase 9
--  leaves the pre-warranty view, re-created below.)
CREATE VIEW stock_movement AS
SELECT 'RAW'::text AS kind, pd.pid, pd.pname, p.branch_id, p.date, 'PINV', p.id, pd.qty, pd.price, NULL
FROM purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'RAW'
UNION ALL
SELECT 'RAW', prd.pid, prd.pname, pr.branch_id, pr.date, 'PRINV', pr.id, -prd.qty, prd.price, NULL
FROM purchase_return_detail prd JOIN purchase_return pr ON pr.id = prd.purchase_id
UNION ALL
SELECT 'RAW', pid.pid, pid.pname, i.branch_id, i.date, 'PISSUE', i.id, -pid.qty, pid.price, NULL
FROM production_issue_detail pid JOIN production_issue i ON i.id = pid.issue_id
UNION ALL
SELECT 'FINISH', pd.pid, pd.pname, p.branch_id, p.date, 'PINV', p.id, pd.qty, pd.price, 'NEW'
FROM purchase_detail pd JOIN purchase p ON p.id = pd.purchase_id WHERE p.kind = 'FINISH'
UNION ALL
SELECT 'FINISH', o.product_id, NULL, o.branch_id, o.date, 'POUT', o.id, o.qty, o.per_unit, o.grade
FROM production_output o
UNION ALL
SELECT 'FINISH', d.product_id, d.pname, d.branch_id, d.date, 'DAMAGE', d.id, -d.qty, d.value, NULL
FROM damaged_stock d WHERE d.kind = 'BATTERY'
UNION ALL
SELECT 'FINISH', sd.pid, sd.pname, s.branch_id, s.date, 'SINV', s.id, -sd.qty, sd.price, NULL
FROM sale_detail sd JOIN sale s ON s.id = sd.sale_id WHERE sd.line_type = 'PRODUCT'
UNION ALL
SELECT 'FINISH', srd.pid, srd.pname, sr.branch_id, sr.date, 'SRINV', sr.id, srd.qty, srd.price, NULL
FROM sale_return_detail srd JOIN sale_return sr ON sr.id = srd.sale_id
UNION ALL
SELECT COALESCE(dr.type, 'RAW'), drd.pid, drd.pname, dr.from_branch, dr.date, 'BTINV', dr.id, -drd.qty, drd.price, NULL
FROM do_request_detail drd JOIN do_request dr ON dr.id = drd.inv_id WHERE dr.status IN ('DESPATCHED', 'RECEIVED')
UNION ALL
SELECT COALESCE(rc.type, 'RAW'), rcd.pid, rcd.pname, rc.to_branch, rc.date, 'DORINV', rc.id, rcd.qty, rcd.price, NULL
FROM do_received_detail rcd JOIN do_received rc ON rc.id = rcd.inv_id;

DELETE FROM document_counter WHERE doc_type = 'WARRANTY';
DELETE FROM account WHERE account_id = 5010104;
DROP TABLE IF EXISTS warranty_part;
DROP TABLE IF EXISTS warranty_claim_detail;
DROP TABLE IF EXISTS warranty_claim;
DROP TABLE IF EXISTS warranty_hold;

DELETE FROM role_assign WHERE form_id = 57;
DELETE FROM forms_action WHERE form_id = 57;
DELETE FROM form WHERE id = 57;
