-- Up Migration
--
-- PHASE 7 — selling. (PLAN.md Phase 7, SPECS §8, PRINCIPLES §7)
--
-- The sale document already exists; this gives it the two things the old app
-- lacked and the business needs:
--   * service/charge lines on an invoice (revenue with no stock movement),
--   * credit customers with a settlement cycle, an optional credit limit, and
--     advances that are applied against the next bill.

-- =============================================================================
-- 1. Custom service lines on a sale
-- =============================================================================

ALTER TABLE sale_detail
    ADD COLUMN line_type text NOT NULL DEFAULT 'PRODUCT';

ALTER TABLE sale_detail
    ADD CONSTRAINT sale_detail_line_type_check CHECK (line_type IN ('PRODUCT', 'SERVICE'));

-- =============================================================================
-- 2. Credit customers — settlement cycle and credit limit
-- =============================================================================

ALTER TABLE customer
    ADD COLUMN settlement_cycle text,
    ADD COLUMN credit_limit numeric(18,2) NOT NULL DEFAULT 0;

ALTER TABLE customer
    ADD CONSTRAINT customer_settlement_cycle_check
        CHECK (settlement_cycle IS NULL OR settlement_cycle IN ('WEEKLY', 'MONTHLY'));

-- =============================================================================
-- 3. Advances — a customer pays before the bill
-- =============================================================================

CREATE TABLE customer_advance (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customer(id),
    branch_id   integer NOT NULL REFERENCES branch(id),
    date        date NOT NULL,
    amount      numeric(18,2) NOT NULL DEFAULT 0,
    method      text NOT NULL DEFAULT 'CASH',
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT customer_advance_method_check CHECK (method IN ('CASH', 'BANK'))
);

-- Down Migration
DROP TABLE IF EXISTS customer_advance;

ALTER TABLE customer
    DROP CONSTRAINT IF EXISTS customer_settlement_cycle_check,
    DROP COLUMN IF EXISTS credit_limit,
    DROP COLUMN IF EXISTS settlement_cycle;

ALTER TABLE sale_detail
    DROP CONSTRAINT IF EXISTS sale_detail_line_type_check,
    DROP COLUMN IF EXISTS line_type;
