-- Up Migration
--
-- PHASE 8 — lab and expenses. (PLAN.md Phase 8, SPECS §3.6/§3.7/§9/§12,
-- PRINCIPLES §9)
--
-- Lab: repair job types are a central list; each branch sets its own price.
-- A job records the customer, the fault, the parts consumed, a required
-- description and the charge. A lab repair never creates stock — parts out,
-- money in, no finished-goods movement.
--
-- Expenses: one branch, one date, one category, a description, seeded from the
-- central category list so branches compare on the same rows.

-- =============================================================================
-- 1. Repair job types — a central list
-- =============================================================================

CREATE TABLE repair_type (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

-- =============================================================================
-- 2. Branch repair prices — one per branch x job type
-- =============================================================================

CREATE TABLE branch_repair_price (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id       integer NOT NULL REFERENCES branch(id),
    repair_type_id  integer NOT NULL REFERENCES repair_type(id) ON DELETE CASCADE,
    price           numeric(18,2) NOT NULL DEFAULT 0,
    minimum_price   numeric(18,2) NOT NULL DEFAULT 0,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    created_by      integer NOT NULL DEFAULT 0,
    updated_by      integer NOT NULL DEFAULT 0,
    CONSTRAINT branch_repair_price_unique UNIQUE (branch_id, repair_type_id)
);

-- Fan-out both ways, like branch_product.
CREATE FUNCTION branch_repair_price_from_type() RETURNS trigger
LANGUAGE plpgsql AS $fanout_type$
BEGIN
    INSERT INTO branch_repair_price (branch_id, repair_type_id, created_by, updated_by)
    SELECT b.id, NEW.id, NEW.created_by, NEW.created_by
    FROM   branch b
    WHERE  b.id > 0 AND b.is_active
    ON CONFLICT (branch_id, repair_type_id) DO NOTHING;
    RETURN NEW;
END;
$fanout_type$;

CREATE FUNCTION branch_repair_price_from_branch() RETURNS trigger
LANGUAGE plpgsql AS $fanout_branch$
BEGIN
    IF NEW.id = 0 OR NOT NEW.is_active THEN
        RETURN NEW;
    END IF;

    INSERT INTO branch_repair_price (branch_id, repair_type_id, created_by, updated_by)
    SELECT NEW.id, rt.id, NEW.created_by, NEW.created_by
    FROM   repair_type rt
    WHERE  rt.is_active
    ON CONFLICT (branch_id, repair_type_id) DO NOTHING;
    RETURN NEW;
END;
$fanout_branch$;

CREATE TRIGGER trg_branch_repair_price_from_type
    AFTER INSERT ON repair_type
    FOR EACH ROW EXECUTE FUNCTION branch_repair_price_from_type();

CREATE TRIGGER trg_branch_repair_price_from_branch
    AFTER INSERT OR UPDATE OF is_active ON branch
    FOR EACH ROW EXECUTE FUNCTION branch_repair_price_from_branch();

-- =============================================================================
-- 3. Lab intake — job type, fault, and the required work description
-- =============================================================================

ALTER TABLE lab_received
    ADD COLUMN repair_type_id integer REFERENCES repair_type(id),
    ADD COLUMN fault text,
    ADD COLUMN description text;

-- =============================================================================
-- 4. Expense categories and a "Food & Refreshment" account
-- =============================================================================

INSERT INTO account (name, account_id, head_id, sub_head_id, head_code, sub_code, third, is_fixed)
SELECT 'Food & Refreshment', 5020310, 5, 9, 5, 2, 3, true
WHERE NOT EXISTS (SELECT 1 FROM account WHERE account_id = 5020310);

CREATE TABLE expense_category (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    account_id  integer NOT NULL REFERENCES account(account_id),
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0
);

INSERT INTO expense_category (name, account_id) VALUES
    ('Rent',          5020301),
    ('Electricity',   5020302),
    ('Food',          5020310),
    ('Transport',     5020306),
    ('Salaries',      5020101),
    ('Repairs',       5020304),
    ('Miscellaneous', 5020309);

-- =============================================================================
-- 5. Expenses
-- =============================================================================

CREATE TABLE expense (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   integer NOT NULL REFERENCES branch(id),
    date        date NOT NULL,
    category_id integer NOT NULL REFERENCES expense_category(id),
    amount      numeric(18,2) NOT NULL DEFAULT 0,
    method      text NOT NULL DEFAULT 'CASH',
    description text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_by  integer NOT NULL DEFAULT 0,
    updated_by  integer NOT NULL DEFAULT 0,
    CONSTRAINT expense_method_check CHECK (method IN ('CASH', 'BANK'))
);

-- Down Migration
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS expense_category;
DELETE FROM account WHERE account_id = 5020310;

ALTER TABLE lab_received
    DROP COLUMN IF EXISTS description,
    DROP COLUMN IF EXISTS fault,
    DROP COLUMN IF EXISTS repair_type_id;

DROP TRIGGER IF EXISTS trg_branch_repair_price_from_branch ON branch;
DROP TRIGGER IF EXISTS trg_branch_repair_price_from_type ON repair_type;
DROP FUNCTION IF EXISTS branch_repair_price_from_branch();
DROP FUNCTION IF EXISTS branch_repair_price_from_type();
DROP TABLE IF EXISTS branch_repair_price;
DROP TABLE IF EXISTS repair_type;
