-- Up Migration
--
-- PHASE 2 — login history. (PLAN.md Phase 2, SPECS §9)
--
-- Records who signed in, when, and from where. Successes only: a failed
-- attempt has no user_id to attach to and drifts into brute-force-detection
-- scope nobody asked for. A clean additive migration later if ever needed.
--
-- Login History sits beside the existing Activity Log (form 38 / 804) in the
-- same "User Management" head (8), so it is a new FORM under the existing
-- head, not a new head — it needs no different permission scope.

CREATE TABLE login_history (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES user_logins(id),
    username    text    NOT NULL,
    branch_id   integer NOT NULL,
    ip          text,
    user_agent  text,
    at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_login_history_user   ON login_history(user_id, at DESC);
CREATE INDEX idx_login_history_branch ON login_history(branch_id, at DESC);

-- Permission: form 54 / form code 805 / action 8051 (View only).
INSERT INTO form (id, head_id, form_name, sub, sr, ids, form_code)
VALUES (54, 8, 'Login History', NULL, 5, 54, 805)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('form', 'id'),
              GREATEST((SELECT MAX(id) FROM form), 1));

INSERT INTO forms_action (form_id, action_name, sr, action_code)
SELECT 54, 'View', 1, 8051
WHERE NOT EXISTS (SELECT 1 FROM forms_action WHERE form_id = 54 AND action_code = 8051);

-- Down Migration
DELETE FROM role_assign WHERE form_id = 54;
DELETE FROM forms_action WHERE form_id = 54;
DELETE FROM form WHERE id = 54;

DROP TABLE IF EXISTS login_history;
